name: Build

on:
  push:
    branches:
      - main

jobs:  
  build_java11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Configure git
        run: |
          git config --global committer.email "noreply@github.com"
          git config --global committer.name "GitHub"
          git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global author.name "${GITHUB_ACTOR}"      
      - name: Build with Maven
        run: mvn -Pproduction spring-boot:build-image
        env:
          CONTAINER_REGISTRY_USERNAME: ${{ secrets.CR_PAT }}        
          CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CR_PAT }}
          CONTAINER_REGISTRY_URL: ghcr.io
          CONTAINER_REPOSITORY: ${GITHUB_REPOSITORY_OWNER}